# Generated by Django 4.0.2 on 2022-03-15 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComputerBrands',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brandname', models.CharField(max_length=50)),
                ('logo', models.ImageField(upload_to='uploads/products/')),
            ],
        ),
        migrations.CreateModel(
            name='ComputerSpecification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generation', models.CharField(max_length=50)),
                ('price_min', models.IntegerField(default=0)),
                ('price_max', models.IntegerField(default=0)),
                ('ram', models.IntegerField(default=0)),
                ('computercode', models.IntegerField(default=0)),
                ('brandname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='computer.computerbrands')),
            ],
        ),
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('computercode', models.IntegerField(unique=True)),
                ('brandname', models.CharField(blank=True, max_length=50, null=True)),
                ('quantity', models.IntegerField()),
                ('unitrate', models.IntegerField()),
                ('totalprice', models.IntegerField()),
                ('computer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='computer.computerspecification')),
            ],
        ),
    ]
