# Generated by Django 4.0.2 on 2022-03-15 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('computer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='computerspecification',
            name='computercode',
        ),
    ]
